language: cpp
dist: bionic
services:
- docker
addons:
  apt:
    packages:
    - qemu-user-static
    - jq
    - tree

env:
- DOCKER_CLI_EXPERIMENTAL=enabled BASE_IMAGE_TAG="v2.4.0"

branches:
  only:
  - main
  - develop
  - "/^v\\d+\\.\\d+\\.\\d+(-S*)?$/"
  - "/.*\\.(?i:build)$/"

before_install:
- openssl aes-256-cbc -K $encrypted_f6748e572ec7_key -iv $encrypted_f6748e572ec7_iv
  -in .deploy_key.enc -out .deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./.deploy_key
- ssh-add ./.deploy_key

jobs:
  include:
  ## build arch-specific images
  - stage: build images
    name: amd64
    before_install: ".travis/setup_emulation.sh"
    script:
    - set -e
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - ".travis/bootstrap_image.sh -u driplineorg -r dripline-cpp -t ${BASE_IMAGE_TAG} -a amd64 -i driplineorg/dripline-python:`echo
      ${TRAVIS_BRANCH} | tr / _`"
  - stage: build images
    name: arm32v7
    before_install: ".travis/setup_emulation.sh"
    script:
    - set -e
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - ".travis/bootstrap_image.sh -u driplineorg -r dripline-cpp -t ${BASE_IMAGE_TAG} -a arm7 -i driplineorg/dripline-python:`echo
      ${TRAVIS_BRANCH} | tr / _`"

  ## build general-use manifest
  - stage: assemble manifest
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - ".travis/build_manifest.sh -a arm -a amd64 -n driplineorg/dripline-python:`echo
      ${TRAVIS_BRANCH} | tr / _`"

  ## Builds documentation
  - stage: build docs
    git:
      depth: false
    script: .travis/build_docs.sh
