language: cpp

dist: bionic

services:
  - docker

addons:
  apt:
    packages:
      - qemu-user-static
      - jq

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

branches:
  only:
    # dripline v2 main branches
    - master
    - develop
    # dripline v3 main branches
    - dl3/develop
    - dl3/master
    # all version tags
    - /^v\d+\.\d+\.\d+(-S*)?$/
    # all branches ending in '/build' (case insensitive)
    - /.*\/(?i:build)$/

jobs:
  include:
    ## stage for building and publishing docs to github pages
    ##TODO: This should move to after the build/publish of images
    ##TODO: this should use the built/published image
    - stage: build docs
      git:
        depth: false
      #if: branch IN (master, develop) OR branch =~ /^v\d+\.\d+\.\d+(-S*)?$/
      script:
        - docker build -f Dockerfile.docs -t docs_image --build-arg img_tag=develop .
        #- docker build -f Dockerfile.docs -t docs_image --build-arg img_tag=$(echo ${TRAVIS_BRANCH} | tr / _) .
        - docker cp $(docker create docs_image):/root/build/doc/_build/html /tmp/build.html
        - git checkout gh-pages
        - git clean -d -f -x
        - ls
        - rsync -av --delete /tmp/build.html ./$(if [[ "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_BRANCH" == "master" ]]; then echo "$TRAVIS_BRANCH"; elif [[ ! -z "$TRAVIS_TAG" ]]; then echo "tags/$TRAVIS_TAG"; else echo "branches/$(echo $TRAVIS_BRANCH | tr / _ | tr - .)"; fi)
        - tree -L 3

    ## amd64
    - stage: build images
      name: amd64
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u amd64 -r python -t 3.5 -a amd64 -i driplineorg/dripline-python:`echo ${TRAVIS_BRANCH} | tr / _`
    ## arm
    - stage: build images
      name: arm32v7
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u arm32v7 -r python -t 3.5 -a arm7 -i driplineorg/dripline-python:`echo ${TRAVIS_BRANCH} | tr / _`
    - stage: assemble manifest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/build_manifest.sh -a arm -a amd64 -n driplineorg/dripline-python:`echo ${TRAVIS_BRANCH} | tr / _`


