language: cpp

dist: bionic

services:
  - docker

addons:
  apt:
    packages:
      - qemu-user-static
      - jq

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

branches:
  only:
    - master
    - develop
    - develop_dl3
    - feature/fix-travis-builds
    - /^v\d+\.\d+\.\d+(-S*)?$/

jobs:
  include:
    ## amd64
    - stage: build images
      name: amd64
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u amd64 -r python -t 3.5 -a amd64 -i driplineorg/dripline-python:`echo ${TRAVIS_BRANCH} | tr / _`
    ## arm
    - stage: build images
      name: arm32v7
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u arm32v7 -r python -t 3.5 -a arm7 -i driplineorg/dripline-python:`echo ${TRAVIS_BRANCH} | tr / _`
    - stage: assemble manifest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/build_manifest.sh -a arm -a amd64 -n driplineorg/dripline-python:`echo ${TRAVIS_BRANCH} | tr / _`
