version: '2'

services:
  pybind:
    build: .
    volumes:
      #- .:/usr/local/src
      #- ./module_bindings:/usr/local/src/module_bindings
      #- ./CMakeLists.txt:/usr/local/src/CMakeLists.txt
      #- ./setup.py:/usr/local/src/setup.py
      - .:/usr/local/src
      - ./auths.json:/root/p8_auths.json
  rabbit-broker:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=dline
      - RABBITMQ_DEFAULT_PASS=dline
