name: Run Tests

on:
  push:
    branches: [ '*.build' ]
  pull_request:
    branches: '*'

  workflow_dispatch:

jobs:

  test_docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          build-args: |
            img_user=driplineorg
            img_repo=dripline-cpp
            img_tag=2.6.3
          platforms: linux/amd64
